<a href="https://colab.research.google.com/github/bobur-amirov/Pytorch_example/blob/master/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor

random_tensor = torch.rand(size=(7, 7))
random_tensor

tensor([[0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237],
        [0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967],
        [0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor2 = torch.rand(size=(1, 7))


# Perform matrix multiplication 
random_tensor * random_tensor2.T

tensor([[0.0709, 0.1959, 0.4308, 0.5656, 0.5784, 0.5822, 0.3708],
        [0.0454, 0.3801, 0.1303, 0.0237, 0.6574, 0.6128, 0.0009],
        [0.3146, 0.2203, 0.2214, 0.1437, 0.3669, 0.1080, 0.3621],
        [0.1928, 0.2197, 0.1759, 0.0013, 0.0450, 0.1919, 0.1548],
        [0.0810, 0.1562, 0.7148, 0.6165, 0.2077, 0.2756, 0.0175],
        [0.0100, 0.0025, 0.0023, 0.0096, 0.0117, 0.0060, 0.0162],
        [0.0399, 0.1942, 0.1716, 0.0160, 0.0765, 0.1064, 0.1167]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(size=(7, 7))
tensor2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
tensor1 * tensor2

tensor([[0.2392, 0.6298, 0.0882, 0.0922, 0.1745, 0.5296, 0.1008],
        [0.4320, 0.3735, 0.6305, 0.2437, 0.2280, 0.0186, 0.0347],
        [0.1416, 0.4251, 0.6956, 0.5588, 0.0914, 0.2358, 0.1401],
        [0.4411, 0.3255, 0.8716, 0.2929, 0.3138, 0.7958, 0.0074],
        [0.0893, 0.3061, 0.3042, 0.6509, 0.0998, 0.2254, 0.0310],
        [0.0153, 0.1706, 0.9271, 0.5050, 0.4213, 0.4396, 0.0501],
        [0.2817, 0.0272, 0.1383, 0.1692, 0.4628, 0.6625, 0.0572]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.is_available()

True


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
from torch.cuda import is_available
# Set random seed
torch.manual_seed(42)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Devise: {device}")

# Create two random tensors on GPU
ten1 = torch.rand(size=(2, 3))
ten2 = torch.rand(size=(2, 3))
tensor_on_gpu1 = ten1.to(device)
tensor_on_gpu2 = ten2.to(device)
print(tensor_on_gpu1)
print(tensor_on_gpu2)


Devise: cuda
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0')
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
print(tensor_on_gpu1, tensor_on_gpu1.shape)
print(tensor_on_gpu2.T, tensor_on_gpu2.T.shape)
tensor_matmul = torch.mm(tensor_on_gpu1, tensor_on_gpu2.T)
print(tensor_matmul)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0') torch.Size([2, 3])
tensor([[0.2566, 0.1332],
        [0.7936, 0.9346],
        [0.9408, 0.5936]], device='cuda:0') torch.Size([3, 2])
tensor([[1.3127, 1.1999],
        [1.1213, 0.8494]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f"Maximum: {tensor_matmul.max()}")
# Find min
print(f"Minimum: {tensor_matmul.min()}")


Maximum: 1.312738299369812
Minimum: 0.8493574261665344


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"Maximum: {tensor_matmul.argmax()}")

# Find arg min
print(f"Minimum: {tensor_matmul.argmin()}")

Maximum: 0
Minimum: 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor
tensor_ = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions

new_tensor_ = torch.squeeze(tensor_)

# Print out tensors and their shapes
print(tensor_, tensor_.shape)
print(new_tensor_, new_tensor_.shape)

tensor([[[[0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423,
           0.6343, 0.3644]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343,
        0.3644]) torch.Size([10])
